name: cepedi-project-venv
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - keras
  - tensorflow
  - nbformat
  - ipykernel
  - openpyxl